#pragma once

#include <Core/ResourceManager/ResourceHandle.h>
#include <RendererCore/Pipeline/Renderer.h>

struct WPerLensFlareData;
class WRenderDataBatch;
using WShaderResourceHandle = WTypedResourceHandle<class WShaderResource>;

/// Implements rendering of lens flares generated by WLensFlareComponent.
///
/// Renders lens flare effects that simulate camera lens artifacts when looking at bright lights.
/// Uses instanced rendering to draw multiple flare elements in one batch.
class W_RENDERERCORE_DLL WLensFlareRenderer : public WRenderer
{
  W_ADD_DYNAMIC_REFLECTION(WLensFlareRenderer, WRenderer);
  W_DISALLOW_COPY_AND_ASSIGN(WLensFlareRenderer);

public:
  WLensFlareRenderer();
  ~WLensFlareRenderer();

  // WRenderer implementation
  virtual void GetSupportedRenderDataTypes(WDynamicArray<const WRTTI*>& out_types) const override;
  virtual void RenderBatch(const WRenderViewContext& renderContext, const WRenderPipelinePass* pPass, const WRenderDataBatch& batch) const override;

protected:
  /// Creates a GPU buffer for per-flare-element instance data.
  WGALBufferHandle CreateLensFlareDataBuffer(WUInt32 uiBufferSize) const;

  /// Destroys a previously created lens flare data buffer.
  void DeleteLensFlareDataBuffer(WGALBufferHandle hBuffer) const;

  /// Fills the lens flare data array with per-instance information from the batch.
  void FillLensFlareData(const WRenderDataBatch& batch) const;

  WShaderResourceHandle m_hShader;
  mutable WDynamicArray<WPerLensFlareData, WAlignedAllocatorWrapper> m_LensFlareData;
};
