#include <JoltPlugin/JoltPluginPCH.h>

W_STATICLINK_LIBRARY(JoltPlugin)
{
  if (bReturn)
    return;

  W_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltActorComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltDynamicActorComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltHeightfieldColliderComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltQueryShapeActorComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltStaticActorComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltTriggerComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltCharacterControllerComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltDefaultCharacterComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltBreakableSlabComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltClothSheetComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltGenerateCollisionComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltHitboxComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRagdollComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRopeComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltSettingsComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltVisColMeshComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltWaterVolumeComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_Jolt6DOFConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConeConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltDistanceConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltFixedConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltGrabObjectComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltHingeConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltPointConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSliderConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSwingTwistConstraintComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Resources_JoltHeightfieldResource);
  W_STATICLINK_REFERENCE(JoltPlugin_Resources_JoltMeshResource);
  W_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeBoxComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCapsuleComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeConvexHullComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCylinderComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeSphereComponent);
  W_STATICLINK_REFERENCE(JoltPlugin_Startup);
  W_STATICLINK_REFERENCE(JoltPlugin_System_JoltContacts);
  W_STATICLINK_REFERENCE(JoltPlugin_System_JoltCore);
  W_STATICLINK_REFERENCE(JoltPlugin_System_JoltWorldModule);
}
