#pragma once

#include <Foundation/Containers/Map.h>
#include <RendererCore/Declarations.h>
#include <RendererCore/Meshes/MeshBufferResource.h>
#include <RendererCore/Pipeline/ViewData.h>
#include <RendererCore/RenderContext/BindGroupBuilder.h>
#include <RendererCore/RenderContext/Implementation/RenderContextStructs.h>
#include <RendererCore/Shader/ConstantBufferStorage.h>
#include <RendererCore/Shader/ShaderStageBinary.h>
#include <RendererCore/ShaderCompiler/PermutationGenerator.h>
#include <RendererFoundation/CommandEncoder/CommandEncoder.h>
#include <RendererFoundation/Device/Device.h>
#include <RendererFoundation/Shader/BindGroup.h>
#include <RendererFoundation/Shader/ShaderUtils.h>

#include <RendererCore/../../../Data/Base/Shaders/Common/GlobalConstants.h>

struct WRenderWorldRenderEvent;

//////////////////////////////////////////////////////////////////////////
// WRenderContext
//////////////////////////////////////////////////////////////////////////

class W_RENDERERCORE_DLL WRenderContext
{
private:
  WRenderContext(WGALCommandEncoder* pCommandEncoder);
  ~WRenderContext();
  friend class WMemoryUtils;

  static WRenderContext* s_pDefaultInstance;
  static WGALCommandEncoder* s_pCommandEncoder;
  static WHybridArray<WRenderContext*, 4> s_Instances;

public:
  static WRenderContext* GetDefaultInstance();
  static WRenderContext* CreateInstance(WGALCommandEncoder* pCommandEncoder);
  static void DestroyInstance(WRenderContext* pRenderer);

public:
  struct Statistics
  {
    Statistics();
    void Reset();

    WUInt32 m_uiFailedDrawcalls;
    WUInt32 m_uiDrawcalls;
    /// Number of triangles that were submitted through DrawMeshBuffer(). Draw calls with another topology are not counted here,
    /// neither are triangles that are generated by the GPU itself (indirect draws, tessellation, geometry shaders).
    WUInt64 m_uiTriangles;
    WUInt32 m_uiModifiedBindGroup[W_GAL_MAX_BIND_GROUPS] = {0};
    WUInt32 m_uiLayoutChanged[W_GAL_MAX_BIND_GROUPS] = {0};
  };

  Statistics GetAndResetStatistics();

  /// The statistics that were gathered during the previous frame.
  ///
  /// The values cover everything that was rendered by the default render context, ie. all views and all passes of the frame,
  /// including shadow map rendering. They are only available in development builds, otherwise all values are zero.
  static const Statistics& GetLastFrameStatistics() { return s_LastFrameStatistics; }

  void BeginRendering(const WGALRenderingSetup& renderingSetup, const WRectFloat& viewport, const char* szName = "", bool bStereoRendering = false);
  void EndRendering();

  void BeginCompute(const char* szName = "");
  void EndCompute();

  // Helper class to automatically end rendering or compute on scope exit
  template <int ScopeType>
  class CommandEncoderScope
  {
    W_DISALLOW_COPY_AND_ASSIGN(CommandEncoderScope);

  public:
    W_ALWAYS_INLINE ~CommandEncoderScope()
    {
      if constexpr (ScopeType == 0)
        m_RenderContext.EndRendering();
      else
        m_RenderContext.EndCompute();

      if (m_pCommandsScope != nullptr)
      {
        WGALDevice::GetDefaultDevice()->EndCommands(m_pCommandsScope);
      }
    }

    W_ALWAYS_INLINE WGALCommandEncoder* operator->() { return m_pGALCommandEncoder; }
    W_ALWAYS_INLINE operator const WGALCommandEncoder*() { return m_pGALCommandEncoder; }

  private:
    friend class WRenderContext;

    W_ALWAYS_INLINE CommandEncoderScope(WRenderContext& renderContext, WGALCommandEncoder* pCommandsScope)
      : m_RenderContext(renderContext)
      , m_pCommandsScope(pCommandsScope)
    {
      m_pGALCommandEncoder = renderContext.GetCommandEncoder();
    }

    WRenderContext& m_RenderContext;
    WGALCommandEncoder* m_pCommandsScope;
    WGALCommandEncoder* m_pGALCommandEncoder;
  };

  using RenderingScope = CommandEncoderScope<0>;
  W_ALWAYS_INLINE static RenderingScope BeginRenderingScope(const WRenderViewContext& viewContext, const WGALRenderingSetup& renderingSetup, const char* szName = "", bool bStereoRendering = false)
  {
    viewContext.m_pRenderContext->BeginRendering(renderingSetup, viewContext.m_pViewData->m_ViewPortRect, szName, bStereoRendering);
    return RenderingScope(*viewContext.m_pRenderContext, nullptr);
  }

  using ComputeScope = CommandEncoderScope<1>;
  W_ALWAYS_INLINE static ComputeScope BeginComputeScope(const WRenderViewContext& viewContext, const char* szName = "")
  {
    viewContext.m_pRenderContext->BeginCompute(szName);
    return ComputeScope(*viewContext.m_pRenderContext, nullptr);
  }

  W_ALWAYS_INLINE WGALCommandEncoder* GetCommandEncoder()
  {
    W_ASSERT_DEBUG(m_pGALCommandEncoder != nullptr, "Outside of BeginCommands / EndCommands scope of the device");
    return m_pGALCommandEncoder;
  }

  // Member Functions
  void SetShaderPermutationVariable(const char* szName, const WTempHashedString& sValue);
  void SetShaderPermutationVariable(const WHashedString& sName, const WHashedString& sValue);

  void BindMaterial(const WMaterialResourceHandle& hMaterial);

  WBindGroupBuilder& GetBindGroup(WUInt32 uiBindGroup = 0);
  void ResetBindGroup(WUInt32 uiBindGroup);
  void ResetBindGroups();

  /// Sets push constants to the given data block.
  /// Note that for platforms that don't support push constants, this is emulated via a constant buffer. Thus, a slot name must be provided as well which matches the name of the BEGIN_PUSH_CONSTANTS block in the shader.
  /// \param sSlotName Name of the BEGIN_PUSH_CONSTANTS block in the shader.
  /// \param data Data of the push constants. If more than 128 bytes, WGALDeviceCapabilities::m_uiMaxPushConstantsSize should be checked to ensure the data block is not too big for the platform.
  void SetPushConstants(WTempHashedString sSlotName, WArrayPtr<const WUInt8> data);

  /// Templated version of SetPushConstants.
  /// \tparam T Type of the push constants struct.
  /// \param sSlotName Name of the BEGIN_PUSH_CONSTANTS block in the shader.
  /// \param constants Instance of type T that contains the push constants.
  template <typename T>
  W_ALWAYS_INLINE void SetPushConstants(WTempHashedString sSlotName, const T& constants)
  {
    SetPushConstants(sSlotName, WArrayPtr<const WUInt8>(reinterpret_cast<const WUInt8*>(&constants), sizeof(T)));
  }

  /// Sets the currently active shader on the given render context.
  ///
  /// This function has no effect until the next draw or dispatch call on the context.
  void BindShader(const WShaderResourceHandle& hShader, WBitflags<WShaderBindFlags> flags = WShaderBindFlags::Default);
  void SetBlendState(WGALBlendStateHandle hBlendState);
  void SetDepthStencilState(WGALDepthStencilStateHandle hDepthStencilState);
  void SetRasterizerState(WGALRasterizerStateHandle hRasterizerState);
  void SetStencilRefValue(WUInt8 uiStencilRefValue);

  void BindMeshBuffer(const WMeshBufferResourceHandle& hMeshBuffer, WGALBufferHandle hDataOffsetsBuffer = {}, WUInt32 uiFirstDataOffset = 0);
  void BindMeshBuffer(const WDynamicMeshBufferResourceHandle& hDynamicMeshBuffer, WGALBufferHandle hDataOffsetsBuffer = {}, WUInt32 uiFirstDataOffset = 0);
  void BindMeshBuffer(WArrayPtr<const WGALBufferHandle> vertexBuffers, WGALBufferHandle hIndexBuffer, WArrayPtr<const WGALVertexAttribute> vertexAttributes, WGALPrimitiveTopology::Enum topology, WUInt32 uiPrimitiveCount, WGALBufferHandle hDataOffsetsBuffer = {}, WUInt32 uiFirstDataOffset = 0);
  W_ALWAYS_INLINE void BindNullMeshBuffer(WGALPrimitiveTopology::Enum topology, WUInt32 uiPrimitiveCount, WGALBufferHandle hDataOffsetsBuffer = {}, WUInt32 uiFirstDataOffset = 0)
  {
    BindMeshBuffer({}, {}, {}, topology, uiPrimitiveCount, hDataOffsetsBuffer, uiFirstDataOffset);
  }

  void BindVertexBuffer(WGALBufferHandle hVertexBuffer, WUInt32 uiSlot, WEnum<WGALVertexBindingRate> rate = WGALVertexBindingRate::Vertex, WUInt32 uiOffset = 0);
  void SetVertexAttributes(WArrayPtr<WGALVertexAttribute> vertexAttributes);

  WResult DrawMeshBuffer(WUInt32 uiPrimitiveCount = 0xFFFFFFFF, WUInt32 uiFirstPrimitive = 0, WUInt32 uiInstanceCount = 1);

  WResult Dispatch(WUInt32 uiThreadGroupCountX, WUInt32 uiThreadGroupCountY = 1, WUInt32 uiThreadGroupCountZ = 1);

  WResult ApplyContextStates(bool bForce = false);

  WGlobalConstants& WriteGlobalConstants();
  const WGlobalConstants& ReadGlobalConstants() const;
  void SetGlobalAndWorldTimeConstants(WTime worldTime);

  /// Sets the texture filtering quality for all quality-adjustable samplers.
  ///
  /// The default quality is Anisotropic4x and is controlled via the Rendering.TextureQuality CVar.
  /// Changing quality triggers immediate recreation of all affected sampler states.
  /// Pass bForce = true to force recreation even if the quality value did not change.
  void SetDefaultTextureQuality(WGALTextureQuality::Enum quality, bool bForce = false);

  /// Returns the texture filter mode that is used by default for textures.
  WGALTextureQuality::Enum GetDefaultTextureQuality() const { return m_DefaultTextureQuality; }

  /// Set async shader loading. During runtime all shaders should be preloaded so this is off by default.
  void SetAllowAsyncShaderLoading(bool bAllow);

  /// Returns async shader loading. During runtime all shaders should be preloaded so this is off by default.
  bool GetAllowAsyncShaderLoading();


  // Static Functions
public:
  // Constant buffer storage handling
  template <typename T>
  W_ALWAYS_INLINE static WConstantBufferStorageHandle CreateConstantBufferStorage()
  {
    return CreateConstantBufferStorage(sizeof(T));
  }

  template <typename T>
  W_FORCE_INLINE static WConstantBufferStorageHandle CreateConstantBufferStorage(WConstantBufferStorage<T>*& out_pStorage)
  {
    WConstantBufferStorageBase* pStorage;
    WConstantBufferStorageHandle hStorage = CreateConstantBufferStorage(sizeof(T), pStorage);
    out_pStorage = static_cast<WConstantBufferStorage<T>*>(pStorage);
    return hStorage;
  }

  W_FORCE_INLINE static WConstantBufferStorageHandle CreateConstantBufferStorage(WUInt32 uiSizeInBytes)
  {
    WConstantBufferStorageBase* pStorage;
    return CreateConstantBufferStorage(uiSizeInBytes, pStorage);
  }

  static WConstantBufferStorageHandle CreateConstantBufferStorage(WUInt32 uiSizeInBytes, WConstantBufferStorageBase*& out_pStorage);
  static void DeleteConstantBufferStorage(WConstantBufferStorageHandle& inout_hStorage);

  template <typename T>
  W_FORCE_INLINE static bool TryGetConstantBufferStorage(WConstantBufferStorageHandle hStorage, WConstantBufferStorage<T>*& out_pStorage)
  {
    WConstantBufferStorageBase* pStorage = nullptr;
    bool bResult = TryGetConstantBufferStorage(hStorage, pStorage);
    out_pStorage = static_cast<WConstantBufferStorage<T>*>(pStorage);
    return bResult;
  }

  static bool TryGetConstantBufferStorage(WConstantBufferStorageHandle hStorage, WConstantBufferStorageBase*& out_pStorage);
  static void MarktConstantBufferStorageModified(WConstantBufferStorageBase* pDirtyStorage);

  template <typename T>
  W_FORCE_INLINE static T* GetConstantBufferData(WConstantBufferStorageHandle hStorage)
  {
    WConstantBufferStorage<T>* pStorage = nullptr;
    if (TryGetConstantBufferStorage(hStorage, pStorage))
    {
      return &(pStorage->GetDataForWriting());
    }

    return nullptr;
  }

  // Default sampler state
  static WGALSamplerStateCreationDescription GetDefaultSamplerState(WBitflags<WDefaultSamplerFlags> flags);

private:
  W_MAKE_SUBSYSTEM_STARTUP_FRIEND(RendererCore, RendererContext);

  void ResetContextState();
  static void LoadBuiltinShader(WShaderUtils::WBuiltinShaderType type, WShaderUtils::WBuiltinShader& out_shader);
  static void RegisterImmutableSamplers();
  static void OnEngineStartup();
  static void OnEngineShutdown();
  static void GALStaticDeviceEventHandler(const WGALDeviceEvent& e);

private:
  static Statistics s_LastFrameStatistics;

  Statistics m_Statistics;
  WBitflags<WRenderContextFlags> m_StateFlags;

  // Material
  WMaterialResourceHandle m_hNewMaterial;
  WMaterialResourceHandle m_hMaterial;
  const WMaterialResource* m_pMaterial = nullptr;      ///< Must never be accessed, just used as key to WMaterialManager::GetMaterialBindGroup
  const WGALBindGroup* m_pMaterialBindGroup = nullptr; ///< Only stored here to assert is we generate a layout missmatch.

  // Shader Resource
  WShaderResourceHandle m_hActiveShader;
  WHashTable<WHashedString, WHashedString> m_PermutationVariables;

  // Shader Permutation
  WShaderPermutationResourceHandle m_hActiveShaderPermutation;
  WString m_sActiveShader;
  WGALShaderHandle m_hActiveGALShader;
  const WGALShader* m_pActiveGALShader = nullptr;
  WBitflags<WShaderBindFlags> m_ShaderBindFlags;

  // Vertex / Index Buffer
  WGALBufferHandle m_hVertexBuffers[W_GAL_MAX_VERTEX_BUFFER_COUNT];
  WUInt32 m_VertexBufferStrides[W_GAL_MAX_VERTEX_BUFFER_COUNT] = {};
  WUInt32 m_VertexBufferOffsets[W_GAL_MAX_VERTEX_BUFFER_COUNT] = {};
  WEnum<WGALVertexBindingRate> m_VertexBufferBindingRates[W_GAL_MAX_VERTEX_BUFFER_COUNT];
  WGALBufferHandle m_hIndexBuffer;
  WSmallArray<WGALVertexAttribute, 16> m_VertexAttributes;

  WUInt32 m_uiMeshBufferPrimitiveCount;
  WEnum<WGALTextureQuality> m_DefaultTextureQuality;
  bool m_bAllowAsyncShaderLoading;
  bool m_bStereoRendering = false;

  WUInt8 m_uiUserStencilRefValue = 0;
  WUInt8 m_uiShaderStencilRefValue = 0;
  bool m_bUseUserStencilRefValue = false;

  WGALGraphicsPipelineCreationDescription m_GraphicsPipeline;
  WGALComputePipelineCreationDescription m_ComputePipeline;
  WBindGroupBuilder m_BindGroupBuilders[W_GAL_MAX_BIND_GROUPS];
  WGALBindGroupCreationDescription m_BindGroups[W_GAL_MAX_BIND_GROUPS];
  bool m_bDirtyBindGroups[W_GAL_MAX_BIND_GROUPS] = {};

  WConstantBufferStorageHandle m_hGlobalConstantBufferStorage;
  WConstantBufferStorageHandle m_hPushConstantsStorage;

  struct ShaderVertexDecl
  {
    WGALShaderHandle m_hShader;
    WUInt32 m_uiVertexAttributesHash;

    W_FORCE_INLINE bool operator<(const ShaderVertexDecl& rhs) const
    {
      if (m_hShader < rhs.m_hShader)
        return true;
      if (rhs.m_hShader < m_hShader)
        return false;
      return m_uiVertexAttributesHash < rhs.m_uiVertexAttributesHash;
    }

    W_FORCE_INLINE bool operator==(const ShaderVertexDecl& rhs) const
    {
      return (m_hShader == rhs.m_hShader && m_uiVertexAttributesHash == rhs.m_uiVertexAttributesHash);
    }
  };

  static WResult BuildVertexDeclaration(WGALShaderHandle hShader, WArrayPtr<WUInt32> vertexBufferStrides, WArrayPtr<WEnum<WGALVertexBindingRate>> vertexBufferBindingRates, WArrayPtr<WGALVertexAttribute> vertexAttributes, WGALVertexDeclarationHandle& out_Declaration);

  static WMap<ShaderVertexDecl, WGALVertexDeclarationHandle> s_GALVertexDeclarations;

  static WMutex s_ConstantBufferStorageMutex;
  static WIdTable<WConstantBufferStorageId, WConstantBufferStorageBase*> s_ConstantBufferStorageTable;
  static WMap<WUInt32, WDynamicArray<WConstantBufferStorageBase*>> s_FreeConstantBufferStorage;
  static WSet<WConstantBufferStorageBase*> s_DirtyConstantBuffers;

private: // Per Renderer States
  WGALCommandEncoder* m_pGALCommandEncoder = nullptr;
  WEventSubscriptionID m_GALdeviceEventsId = 0;
  bool m_bRendering = false;
  bool m_bCompute = false;

  // Member Functions
  void UploadConstants();

  void SetShaderPermutationVariableInternal(const WHashedString& sName, const WHashedString& sValue);
  void BindShaderInternal(const WShaderResourceHandle& hShader, WBitflags<WShaderBindFlags> flags);
  WResult ApplyShaderState();
  void ApplyMaterialState();
  WResult ApplyBindGroup(const WGALShader* pShader, WUInt32 uiBindGroup);
};
