#include <Foundation/FoundationPCH.h>

W_STATICLINK_LIBRARY(Foundation)
{
  if (bReturn)
    return;

  W_STATICLINK_REFERENCE(Foundation_Application_Config_Implementation_FileSystemConfig);
  W_STATICLINK_REFERENCE(Foundation_Application_Config_Implementation_PluginConfig);
  W_STATICLINK_REFERENCE(Foundation_CodeUtils_Expression_Implementation_ExpressionByteCode);
  W_STATICLINK_REFERENCE(Foundation_CodeUtils_Expression_Implementation_ExpressionDeclarations);
  W_STATICLINK_REFERENCE(Foundation_Communication_Implementation_Message);
  W_STATICLINK_REFERENCE(Foundation_Communication_Implementation_MessageLoop);
  W_STATICLINK_REFERENCE(Foundation_Communication_Implementation_RemoteMessage);
  W_STATICLINK_REFERENCE(Foundation_Configuration_Implementation_CVar);
  W_STATICLINK_REFERENCE(Foundation_DataProcessing_Stream_DefaultImplementations_Implementation_ZeroInitializer);
  W_STATICLINK_REFERENCE(Foundation_DataProcessing_Stream_Implementation_ProcessingStreamProcessor);
  W_STATICLINK_REFERENCE(Foundation_IO_Archive_Implementation_DataDirTypeArchive);
  W_STATICLINK_REFERENCE(Foundation_IO_FileSystem_Implementation_DataDirTypeFolder);
  W_STATICLINK_REFERENCE(Foundation_IO_FileSystem_Implementation_FileSystem);
  W_STATICLINK_REFERENCE(Foundation_Logging_Implementation_LogEntry);
  W_STATICLINK_REFERENCE(Foundation_Math_Implementation_Math);
  W_STATICLINK_REFERENCE(Foundation_Math_Implementation_Random);
  W_STATICLINK_REFERENCE(Foundation_Memory_Implementation_FrameAllocator);
  W_STATICLINK_REFERENCE(Foundation_Memory_Implementation_TempAllocator);
  W_STATICLINK_REFERENCE(Foundation_Platform_Win_DirectoryWatcher_Win);
  W_STATICLINK_REFERENCE(Foundation_Profiling_Implementation_Profiling);
  W_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_AbstractProperty);
  W_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_PropertyAttributes);
  W_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_PropertyPath);
  W_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_RTTI);
  W_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_StandardTypes);
  W_STATICLINK_REFERENCE(Foundation_Serialization_Implementation_AbstractObjectGraph);
  W_STATICLINK_REFERENCE(Foundation_Serialization_Implementation_GraphVersioning);
  W_STATICLINK_REFERENCE(Foundation_System_Implementation_StackTracer);
  W_STATICLINK_REFERENCE(Foundation_Threading_Implementation_TaskSystem);
  W_STATICLINK_REFERENCE(Foundation_Threading_Implementation_ThreadUtils);
  W_STATICLINK_REFERENCE(Foundation_Time_Implementation_Clock);
  W_STATICLINK_REFERENCE(Foundation_Time_Implementation_Time);
  W_STATICLINK_REFERENCE(Foundation_Time_Implementation_Timestamp);
  W_STATICLINK_REFERENCE(Foundation_Tracks_Implementation_ColorGradient);
  W_STATICLINK_REFERENCE(Foundation_Tracks_Implementation_Curve1D);
  W_STATICLINK_REFERENCE(Foundation_Tracks_Implementation_CurveEditData);
  W_STATICLINK_REFERENCE(Foundation_Types_Implementation_VarianceTypes);
  W_STATICLINK_REFERENCE(Foundation_Types_Implementation_VariantTypeRegistry);
}
