#include <RendererFoundation/RendererFoundationPCH.h>

W_STATICLINK_LIBRARY(RendererFoundation)
{
  if (bReturn)
    return;

  W_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_ImmutableSamplers);
  W_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_SharedTextureSwapChain);
  W_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_SwapChain);
  W_STATICLINK_REFERENCE(RendererFoundation_Profiling_Implementation_Profiling);
  W_STATICLINK_REFERENCE(RendererFoundation_RendererReflection);
  W_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_RendererFallbackResources);
  W_STATICLINK_REFERENCE(RendererFoundation_State_Implementation_PipelineCache);
}
