#pragma once

#include <Foundation/Basics.h>
#include <Foundation/Reflection/Reflection.h>

#include <RendererFoundation/Descriptors/Descriptors.h>
#include <RendererFoundation/RendererFoundationDLL.h>
#include <RendererFoundation/Resources/Texture.h>

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALMSAASampleCount);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALTextureType);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALTextureUsageFlags);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALResourceAccess);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALTextureCreationDescription);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALPlatformSharedHandle);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALResourceFormat);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALShaderResourceType);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALShaderTextureType);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALShaderStage);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALShaderStageFlags);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALResourceState);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALShaderResourceCategory);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALPresentMode);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALVertexAttributeSemantic);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALBufferUsageFlags);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALQueryType);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALSharedTextureType);

W_DECLARE_REFLECTABLE_TYPE(W_RENDERERFOUNDATION_DLL, WGALQueueType);
