#include <ComputeShaderHistogram/ComputeShaderHistogram.h>

#include <Core/Graphics/Geometry.h>
#include <Core/Input/DeviceTypes/MouseKeyboard.h>
#include <Core/Input/InputManager.h>
#include <Core/System/Window.h>
#include <Core/System/WindowManager.h>
#include <Foundation/Time/Clock.h>
#include <Foundation/Utilities/Stats.h>
#include <GameEngine/GameApplication/WindowOutputTarget.h>
#include <RendererCore/RenderContext/RenderContext.h>
#include <RendererCore/ShaderCompiler/ShaderManager.h>
#include <RendererFoundation/Device/SwapChain.h>
#include <RendererFoundation/Resources/Texture.h>

#include "../../../Data/Samples/ComputeShaderHistogram/Shaders/ClearHistogramParams.h"

static WUInt32 g_uiComputeThreadGroupSize = 32;

WComputeShaderHistogramApp::WComputeShaderHistogramApp()
  : WGameApplication("ComputeShaderHistogram", "Data/Samples/ComputeShaderHistogram")

{
}

WComputeShaderHistogramApp::~WComputeShaderHistogramApp() = default;

void WComputeShaderHistogramApp::Run()
{
  WWindowManager::GetSingleton()->Update();

  WClock::GetGlobalClock()->Update();
  Run_InputUpdate();

#if W_ENABLED(W_SUPPORTS_DIRECTORY_WATCHER)
  m_bStuffChanged = false;
  m_pDirectoryWatcher->EnumerateChanges(WMakeDelegate(&WComputeShaderHistogramApp::OnFileChanged, this));
  if (m_bStuffChanged)
  {
    WResourceManager::ReloadAllResources(false);
  }
#endif

  const WUInt32 uiWindowWidth = m_pWindow->GetClientAreaSize().width;
  const WUInt32 uiWindowHeight = m_pWindow->GetClientAreaSize().height;

  // do the rendering
  {
    auto device = WGALDevice::GetDefaultDevice();

    const WGALSwapChain* pPrimarySwapChain = device->GetSwapChain(m_hSwapChain);
    WGALRenderTargetViewHandle hBackbufferRTV = device->GetDefaultRenderTargetView(pPrimarySwapChain->GetBackBufferTexture());

    // Before starting to render in a frame call this function
    device->EnqueueFrameSwapChain(m_hSwapChain);
    device->BeginFrame();

    WGALCommandEncoder* pCommandEncoder = device->BeginCommands("WComputeShaderHistogram");

    WRenderContext& renderContext = *WRenderContext::GetDefaultInstance();

    // Constant buffer update
    {
      auto& globalConstants = renderContext.WriteGlobalConstants();
      WMemoryUtils::ZeroFill(&globalConstants, 1);

      globalConstants.ViewportSize = WVec4((float)uiWindowWidth, (float)uiWindowHeight, 1.0f / (float)uiWindowWidth, 1.0f / (float)uiWindowHeight);
      // Wrap around to prevent floating point issues. Wrap around is dividable by all whole numbers up to 11.
      globalConstants.GlobalTime = (float)WMath::Mod(WClock::GetGlobalClock()->GetAccumulatedTime().GetSeconds(), 20790.0);
      globalConstants.WorldTime = globalConstants.GlobalTime;
    }

    WRectFloat viewport(0.0f, 0.0f, (float)uiWindowWidth, (float)uiWindowHeight);

    // Draw background.
    {
      WGALRenderingSetup renderingSetup;
      renderingSetup.SetColorTarget(0, m_hScreenRTV);
      renderContext.BeginRendering(renderingSetup, viewport, "Background");

      renderContext.BindShader(m_hRenderScreenShader);
      renderContext.BindNullMeshBuffer(WGALPrimitiveTopology::Triangles, 1); // Vertices are generated by shader.
      renderContext.DrawMeshBuffer().IgnoreResult();


      renderContext.EndRendering();
    }

    // Render screen texture to backbuffer
    {
      WGALRenderingSetup renderingSetup;
      renderingSetup.SetColorTarget(0, hBackbufferRTV);
      renderContext.BeginRendering(renderingSetup, viewport, "Blit");
      WBindGroupBuilder& bindGroupSample = WRenderContext::GetDefaultInstance()->GetBindGroup();
      bindGroupSample.BindTexture("Input", m_hScreenTexture);
      renderContext.BindShader(m_hDisplayScreenShader);
      renderContext.BindNullMeshBuffer(WGALPrimitiveTopology::Triangles, 1);
      renderContext.DrawMeshBuffer().IgnoreResult();
      renderContext.EndRendering();
    }

    // Compute histogram.
    {
      renderContext.BeginCompute("ComputeHistogram");

      WBindGroupBuilder& bindGroupSample = WRenderContext::GetDefaultInstance()->GetBindGroup();
      // Reset first.
      renderContext.BindShader(m_hClearHistogramShader);
      ClearHistogramParams params;
      params.Height = 3;
      params.Width = 256;
      renderContext.SetPushConstants("ClearHistogramParams", params);
      bindGroupSample.BindTexture("HistogramOutput", m_hHistogramTexture);
      renderContext.Dispatch(256 / 16, 1, 1).IgnoreResult();

      // Compute histogram
      renderContext.BindShader(m_hComputeHistogramShader);
      bindGroupSample.BindTexture("ScreenTexture", m_hScreenTexture);
      bindGroupSample.BindTexture("HistogramOutput", m_hHistogramTexture);
      renderContext.Dispatch(uiWindowWidth / g_uiComputeThreadGroupSize + (uiWindowWidth % g_uiComputeThreadGroupSize != 0 ? 1 : 0), uiWindowHeight / g_uiComputeThreadGroupSize + (uiWindowHeight % g_uiComputeThreadGroupSize != 0 ? 1 : 0)).IgnoreResult();

      renderContext.EndCompute();
    }

    // Draw histogram.
    {
      WGALRenderingSetup renderingSetup;
      renderingSetup.SetColorTarget(0, hBackbufferRTV);
      renderContext.BeginRendering(renderingSetup, viewport, "DrawHistogram");

      renderContext.BindShader(m_hDisplayHistogramShader);
      renderContext.BindMeshBuffer(m_hHistogramQuadMeshBuffer);
      WBindGroupBuilder& bindGroupSample = renderContext.GetBindGroup();
      bindGroupSample.BindTexture("HistogramTexture", m_hHistogramTexture);
      renderContext.DrawMeshBuffer().IgnoreResult();

      renderContext.EndRendering();
    }

    device->EndCommands(pCommandEncoder);

    device->EndFrame();
  }

  // needs to be called once per frame
  WResourceManager::PerFrameUpdate();

  // tell the task system to finish its work for this frame
  // this has to be done at the very end, so that the task system will only use up the time that is left in this frame for
  // uploading GPU data etc.
  WTaskSystem::FinishFrameTasks();
}

void WComputeShaderHistogramApp::AfterCoreSystemsStartup()
{
  SUPER::AfterCoreSystemsStartup();
#if W_ENABLED(W_SUPPORTS_DIRECTORY_WATCHER)
  m_pDirectoryWatcher = W_DEFAULT_NEW(WDirectoryWatcher);
  W_VERIFY(m_pDirectoryWatcher->OpenDirectory(FindProjectDirectory(), WDirectoryWatcher::Watch::Writes | WDirectoryWatcher::Watch::Subdirectories).Succeeded(), "Failed to watch project directory");
#endif
  auto device = WGALDevice::GetDefaultDevice();

  if (auto pInput = WInputManager::GetInputDeviceOfType<WInputDeviceMouseKeyboard>())
  {
    pInput->SetShowMouseCursor(true);
    pInput->SetClipMouseCursor(WMouseCursorClipMode::NoClip);
  }

  // Retrieve window and swapchain handle for rendering
  {
    auto pWinMan = WWindowManager::GetSingleton();

    WTempHybridArray<WRegisteredWndHandle, 8> windowIds;
    pWinMan->GetRegistered(windowIds);

    for (auto id : windowIds)
    {
      m_pWindow = pWinMan->GetWindow(id);

      // Retrieve only the first output target
      if (auto pOutput = pWinMan->GetOutputTarget(id))
      {
        m_hSwapChain = static_cast<WWindowOutputTargetGAL*>(pOutput)->m_hSwapChain;
        break;
      }
    }

    W_ASSERT_DEV(m_pWindow != nullptr, "Failed to retrieve active window. No window plugins have been registered.");
    W_ASSERT_DEV(!m_hSwapChain.IsInvalidated(), "Failed to retrieve active window output target.");
  }

  // Create textures and texture view for screen content (can't use back-buffer as shader resource view)
  {
    WGALTextureCreationDescription texDesc;
    texDesc.m_uiWidth = m_pWindow->GetClientAreaSize().width;
    texDesc.m_uiHeight = m_pWindow->GetClientAreaSize().height;
    texDesc.m_Format = WGALResourceFormat::RGBAUByteNormalized; // WGALResourceFormat::RGBAUByteNormalizedsRGB;
    texDesc.m_TextureFlags = WGALTextureUsageFlags::RenderTarget | WGALTextureUsageFlags::ShaderResource;

    m_hScreenTexture = device->CreateTexture(texDesc);
    m_hScreenRTV = device->GetDefaultRenderTargetView(m_hScreenTexture);
  }

  // Create texture for histogram data.
  {
    WGALTextureCreationDescription texDesc;
    texDesc.m_uiWidth = 256;
    texDesc.m_uiHeight = 3; // R, G, B
    texDesc.m_uiMipLevelCount = 1;
    texDesc.m_Format = WGALResourceFormat::RUInt;
    texDesc.m_TextureFlags = WGALTextureUsageFlags::ShaderResource | WGALTextureUsageFlags::UnorderedAccess;
    texDesc.m_ResourceAccess.m_bImmutable = false;

    m_hHistogramTexture = device->CreateTexture(texDesc);
  }

  // Setup Shaders and Materials
  {
    m_hRenderScreenShader = WResourceManager::LoadResource<WShaderResource>("Shaders/RenderScreen.WShader");
    m_hDisplayScreenShader = WResourceManager::LoadResource<WShaderResource>("Shaders/DisplayScreen.WShader");
    m_hClearHistogramShader = WResourceManager::LoadResource<WShaderResource>("Shaders/ClearHistogram.WShader");
    m_hComputeHistogramShader = WResourceManager::LoadResource<WShaderResource>("Shaders/ComputeHistogram.WShader");
    m_hDisplayHistogramShader = WResourceManager::LoadResource<WShaderResource>("Shaders/DisplayHistogram.WShader");
  }

  // Geometry.
  CreateHistogramQuad();
}

void WComputeShaderHistogramApp::BeforeHighLevelSystemsShutdown()
{
  auto device = WGALDevice::GetDefaultDevice();

  m_hRenderScreenShader.Invalidate();
  m_hDisplayScreenShader.Invalidate();
  m_hClearHistogramShader.Invalidate();
  m_hComputeHistogramShader.Invalidate();
  m_hDisplayHistogramShader.Invalidate();

  m_hHistogramQuadMeshBuffer.Invalidate();

  m_hScreenRTV.Invalidate();
  device->DestroyTexture(m_hScreenTexture);
  m_hScreenTexture.Invalidate();

  device->DestroyTexture(m_hHistogramTexture);
  m_hHistogramTexture.Invalidate();

  SUPER::BeforeHighLevelSystemsShutdown();
}

void WComputeShaderHistogramApp::CreateHistogramQuad()
{
  m_hHistogramQuadMeshBuffer = WResourceManager::GetExistingResource<WMeshBufferResource>("{4BEFA142-FEDB-42D0-84DC-58223ADD8C62}");

  if (!m_hHistogramQuadMeshBuffer.IsValid())
  {
    WVec2 pixToScreen(1.0f / m_pWindow->GetClientAreaSize().width * 0.5f, 1.0f / m_pWindow->GetClientAreaSize().height * 0.5f);
    const float borderOffsetPix = 80.0f;
    const float sizeScreen = 0.8f;

    WGeometry geom;
    WGeometry::GeoOptions opt;
    opt.m_Color = WColor::Black;
    opt.m_Transform = WMat4(WMat3::MakeIdentity(), WVec3(1.0f - pixToScreen.x * borderOffsetPix - sizeScreen / 2, -1.0f + pixToScreen.y * borderOffsetPix + sizeScreen / 2, 0.0f));
    geom.AddRect(WVec2(sizeScreen, sizeScreen), 1, 1, opt);

    WMeshBufferResourceDescriptor desc;
    desc.AddCommonStreams();
    desc.AllocateStreamsFromGeometry(geom);

    WUInt32 t = 0;
    for (WUInt32 p = 0; p < geom.GetPolygons().GetCount(); ++p)
    {
      for (WUInt32 v = 0; v < geom.GetPolygons()[p].m_Vertices.GetCount() - 2; ++v)
      {
        desc.SetTriangleIndices(t, geom.GetPolygons()[p].m_Vertices[0], geom.GetPolygons()[p].m_Vertices[v + 1], geom.GetPolygons()[p].m_Vertices[v + 2]);

        ++t;
      }
    }

    m_hHistogramQuadMeshBuffer = WResourceManager::GetOrCreateResource<WMeshBufferResource>("{4BEFA142-FEDB-42D0-84DC-58223ADD8C62}", std::move(desc));
  }
}
#if W_ENABLED(W_SUPPORTS_DIRECTORY_WATCHER)
void WComputeShaderHistogramApp::OnFileChanged(WStringView sFilename, WDirectoryWatcherAction action, WDirectoryWatcherType type)
{
  if (action == WDirectoryWatcherAction::Modified && type == WDirectoryWatcherType::File)
  {
    WLog::Info("The file {0} was modified", sFilename);
    m_bStuffChanged = true;
  }
}
#endif
W_APPLICATION_ENTRY_POINT(WComputeShaderHistogramApp);
