#pragma once

#include <Core/CoreDLL.h>
#include <Core/World/Declarations.h>
#include <Foundation/Strings/StringView.h>

/// Wraps a game object handle such that it is logged as a clickable link.
///
/// The log message will contain a link in the form '[[Display Text|WObject:<handle>]]'. Such a link is only
/// meaningful inside the editor: when the message is forwarded from the engine process to the editor,
/// the handle is translated into the document and object GUID that the editor can navigate to.
/// In all other contexts (game runtime, log files, console) the link markup is simply part of the text.
///
/// If no display text is given, the name of the game object is used, or its handle value, if the object
/// doesn't exist anymore or has no name.
///
/// Example:
///   WLog::Error("Object {} has an invalid setup.", WArgGameObject(hObject));
struct WArgGameObject
{
  inline explicit WArgGameObject(WGameObjectHandle hObject, WStringView sDisplayText = {})
    : m_hObject(hObject)
    , m_sDisplayText(sDisplayText)
  {
  }

  /// Convenience overload, so that a game object pointer can be passed in directly.
  W_CORE_DLL explicit WArgGameObject(const WGameObject* pObject, WStringView sDisplayText = {});

  WGameObjectHandle m_hObject;
  WStringView m_sDisplayText;
};

/// Wraps a component handle such that it is logged as a clickable link.
///
/// Works exactly like WArgGameObject, but generates a link of the form '[[Display Text|WComponent:<handle>]]'.
/// Clicking such a link in the editor selects the game object that owns the component.
///
/// If no display text is given, the name of the component's owner is used, prefixed with the component type name.
struct WArgComponent
{
  inline explicit WArgComponent(WComponentHandle hComponent, WStringView sDisplayText = {})
    : m_hComponent(hComponent)
    , m_sDisplayText(sDisplayText)
  {
  }

  /// Convenience overload, so that a component pointer can be passed in directly.
  W_CORE_DLL explicit WArgComponent(const WComponent* pComponent, WStringView sDisplayText = {});

  WComponentHandle m_hComponent;
  WStringView m_sDisplayText;
};

W_CORE_DLL WStringView BuildString(char* szTmp, WUInt32 uiLength, const WArgGameObject& arg);
W_CORE_DLL WStringView BuildString(char* szTmp, WUInt32 uiLength, const WArgComponent& arg);

/// Utilities to create and parse the link targets generated by WArgGameObject and WArgComponent.
///
/// The editor uses these to translate a handle based link into an 'asset:<doc-guid>#<obj-guid>' link.
/// Runtime code should not need to use this directly.
struct W_CORE_DLL WWorldLogLinkUtils
{
  /// The link scheme used for game object links.
  static constexpr WStringView s_sGameObjectScheme = "WObject:"_wsv;

  /// The link scheme used for component links.
  static constexpr WStringView s_sComponentScheme = "WComponent:"_wsv;

  /// Writes the display text and link target for a game object into out_sResult.
  ///
  /// If sDisplayText is empty, a name is derived from the object, if it can still be found in its world.
  static void AppendGameObjectLink(WStringBuilder& out_sResult, WGameObjectHandle hObject, WStringView sDisplayText);

  /// Same as AppendGameObjectLink() but for components.
  static void AppendComponentLink(WStringBuilder& out_sResult, WComponentHandle hComponent, WStringView sDisplayText);

  /// Extracts a game object handle from a link target that uses s_sGameObjectScheme.
  ///
  /// Returns false if the target doesn't use that scheme or is malformed.
  static bool ParseGameObjectLink(WStringView sLinkTarget, WGameObjectHandle& out_hObject);

  /// Same as ParseGameObjectLink() but for components.
  static bool ParseComponentLink(WStringView sLinkTarget, WComponentHandle& out_hComponent);
};
