function(W_detect_languages)
	set(W_LANGUAGES C CXX PARENT_SCOPE)
	if ((CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows") AND (NOT CMAKE_GENERATOR STREQUAL "Ninja"))
		set(W_LANGUAGES C CXX CSharp PARENT_SCOPE)
	endif()
endfunction()