#pragma once

#include <EditorFramework/EditorFrameworkDLL.h>
#include <Foundation/Containers/Set.h>
#include <Foundation/IO/OSFile.h>
#include <Foundation/IO/Stream.h>
#include <Foundation/Logging/Log.h>
#include <Foundation/Types/Status.h>

struct WPathPatternFilter;
class WAssetCurator;
class WApplicationFileSystemConfig;
class WPlatformProfile;
class WProgressRange;

//////////////////////////////////////////////////////////////////////////

/// The steps around WProjectExport::ExportProjectComplete(), all of which can be skipped.
///
/// The defaults are what the 'Export Project' dialog starts out with, ie. do everything.
struct W_EDITORFRAMEWORK_DLL WProjectExportOptions
{
  /// Build the project's C++ plugin first, so that the exported binaries match the current code.
  /// Has no effect on a project without C++ code.
  bool m_bCompileCppPlugin = true;

  /// Transform all assets first. Without this, assets that were modified since the last transform are
  /// exported in their previous state, and assets never transformed for the active profile are missing
  /// from the export entirely.
  bool m_bTransformAssets = true;

  /// See WProjectExport::ExportProject().
  bool m_bCreateLaunchScripts = true;
};

struct W_EDITORFRAMEWORK_DLL WProjectExport
{
  /// Runs the full export, as triggered by the 'Export Project' dialog.
  ///
  /// Does the optional steps in WProjectExportOptions, then ExportProject() for the currently active
  /// asset profile and the editor's data directory configuration. The target directory is *cleared*
  /// first - see ExportProject().
  ///
  /// Everything that the export logs is captured and written to 'ExportLog.txt' in the target directory,
  /// and returned through out_pLog when that is not null. That means it does not show up in the editor's
  /// log window, so the returned status is the only indication of failure a caller gets without reading
  /// the log.
  static WStatus ExportProjectComplete(WStringView sTargetDirectory, const WProjectExportOptions& options, WStringBuilder* out_pLog = nullptr);


  /// Exports the project to szTargetDirectory.
  ///
  /// If bCreateLaunchScripts is true, .bat files for launching the exported project are written to the target
  /// directory. If the project has a custom game executable (see FindCustomGameExecutable()), a single script for
  /// that executable is created, otherwise one script per exported scene, which launches the scene in WPlayer.
  static WResult ExportProject(const char* szTargetDirectory, const WPlatformProfile* pPlatformProfile, const WApplicationFileSystemConfig& dataDirs, bool bCreateLaunchScripts = true);

  /// Returns the file name of the project's own game executable, or an empty string if there is none.
  ///
  /// The executable is the one generated by the C++ project generation, ie. it is named after the plugin name
  /// in ':project/Editor/CppProject.ddl'. An empty string is returned when the project has no C++ code, or when
  /// the executable hasn't been built yet.
  static WString FindCustomGameExecutable();

private:
  struct DataDirectory
  {
    WString m_sTargetDirPath;
    WString m_sTargetDirRootName;
    WSet<WString> m_Files;
  };

  using DirectoryMapping = WMap<WString, DataDirectory>;

  static WResult ClearTargetFolder(const char* szAbsFolderPath);
  static WResult ScanFolder(WSet<WString>& out_Files, const char* szFolder, const WPathPatternFilter& filter, WAssetCurator* pCurator, WDynamicArray<WString>* pSceneFiles, const WPlatformProfile* pPlatformProfile);
  static WResult CopyFiles(const char* szSrcFolder, const char* szDstFolder, const WSet<WString>& files, WProgressRange* pProgressRange);
  static WResult GatherGeneratedAssetManagerFiles(WSet<WString>& out_Files);
  static WResult CreateExportFilterFile(const char* szExpectedFile, const char* szFallbackFile);
  static WResult ReadExportFilters(WPathPatternFilter& out_DataFilter, WPathPatternFilter& out_BinariesFilter, const WPlatformProfile* pPlatformProfile);
  static WResult CreateDataDirectoryDDL(const DirectoryMapping& mapping, const char* szTargetDirectory);
  static WResult GatherAssetLookupTableFiles(DirectoryMapping& mapping, const WApplicationFileSystemConfig& dirConfig, const WPlatformProfile* pPlatformProfile);
  static WResult ScanDataDirectories(DirectoryMapping& mapping, const WApplicationFileSystemConfig& dirConfig, const WPathPatternFilter& dataFilter, WDynamicArray<WString>* pSceneFiles, const WPlatformProfile* pPlatformProfile);
  static WResult CopyAllFiles(DirectoryMapping& mapping, const char* szTargetDirectory);
  static WResult GatherBinaries(DirectoryMapping& mapping, const WPathPatternFilter& filter);
  static WResult CreateLaunchConfig(const WDynamicArray<WString>& sceneFiles, const char* szTargetDirectory, WStringView sCustomGameExecutable);
  static WResult GatherGeneratedAssetFiles(WSet<WString>& out_Files, const char* szProjectDirectory);
  static void AddPackageDependenciesToFileList(DirectoryMapping& ref_fileList);
};
