#include <GameComponentsPlugin/GameComponentsPCH.h>


W_STATICLINK_LIBRARY(GameComponentsPlugin)
{
  if (bReturn)
    return;

  W_STATICLINK_REFERENCE(GameComponentsPlugin_Animation_Implementation_CreatureCrawlComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Animation_Implementation_MoveToComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Camera_Implementation_ThirdPersonViewComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Debugging_Implementation_LineToComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Effects_Implementation_MeshDecalComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Effects_Shake_Implementation_CameraShakeComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Effects_Shake_Implementation_CameraShakeVolumeComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Gameplay_Implementation_AreaDamageComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Gameplay_Implementation_HeadBoneComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Gameplay_Implementation_PowerConnectorComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Gameplay_Implementation_ProjectileComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Gameplay_Implementation_RaycastComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Physics_Implementation_ClothSheetComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Physics_Implementation_FakeRopeComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Placement_Implementation_RandomPrefabComponent);
  W_STATICLINK_REFERENCE(GameComponentsPlugin_Terrain_Implementation_HeightfieldComponent);
}
