#pragma once

/// \file

#include <Foundation/Reflection/Implementation/AbstractProperty.h>
#include <Foundation/Reflection/Implementation/DynamicRTTI.h>
#include <Foundation/Reflection/Implementation/RTTI.h>
#include <Foundation/Types/Interval.h>
#include <Foundation/Types/Variant.h>

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WEnumBase);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WBitflagsBase);

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WReflectedClass);

// *********************************************
// ***** Standard POD Types for Properties *****

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, bool);

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, float);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, double);

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WInt8);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WUInt8);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WInt16);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WUInt16);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WInt32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WUInt32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WInt64);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WUInt64);

// macros won't work with 'const char*'
using WConstCharPtr = const char*;
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WConstCharPtr);

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WTime);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WColor);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WColorBaseUB);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WColorGammaUB);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WColorLinearUB);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec2);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec3);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec4);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec2I32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec3I32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec4I32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec2U32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec3U32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVec4U32);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WQuat);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WMat3);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WMat4);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WTransform);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WBasisAxis);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WUuid);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WAngle);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WFloatInterval);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WIntInterval);

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVariant);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVariantArray);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVariantDictionary);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WString);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WUntrackedString);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WStringView);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WStringBuilder);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WDataBuffer);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WHashedString);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WTempHashedString);

// **********************************************************************
// ***** Various RTTI infos that can't be put next to their classes *****

W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WTypeFlags);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WPropertyFlags);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WFunctionType);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WVariantType);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WPropertyCategory);
W_DECLARE_REFLECTABLE_TYPE(W_FOUNDATION_DLL, WComparisonOperator);
