#include <Foundation/Application/Application.h>
#include <Foundation/CodeUtils/Tokenizer.h>
#include <Foundation/Configuration/Startup.h>
#include <Foundation/Containers/HashSet.h>
#include <Foundation/Containers/HashTable.h>
#include <Foundation/Containers/Map.h>
#include <Foundation/Containers/Set.h>
#include <Foundation/IO/FileSystem/DataDirTypeFolder.h>
#include <Foundation/IO/FileSystem/FileReader.h>
#include <Foundation/IO/FileSystem/FileSystem.h>
#include <Foundation/IO/JSONReader.h>
#include <Foundation/Logging/ConsoleWriter.h>
#include <Foundation/Logging/HTMLWriter.h>
#include <Foundation/Logging/Log.h>
#include <Foundation/Logging/VisualStudioWriter.h>
#include <Foundation/Memory/LinearAllocator.h>
#include <Foundation/Strings/PathUtils.h>
#include <Foundation/Strings/String.h>
#include <Foundation/Strings/StringBuilder.h>
#include <Foundation/System/SystemInformation.h>
#include <Foundation/Threading/TaskSystem.h>
#include <Foundation/Types/UniquePtr.h>

class WDependencyAnalysisApp;


bool g_bVerbose = false;

namespace
{
  using DependencyListType = WHashSet<WString>;

  struct CompilationUnitContext
  {
    DependencyListType m_dependencies;
    WDynamicArray<WString> m_IncludeDirectories;
    WHashTable<WString, WString> m_includeCache;
  };
  using CompilationUnitListType = WHashTable<WString, CompilationUnitContext>;

  W_ALWAYS_INLINE void SkipWhitespace(WToken& ref_token, WUInt32& i, const WDeque<WToken>& tokens)
  {
    while (ref_token.m_iType == WTokenType::Whitespace)
    {
      ref_token = tokens[++i];
    }
  }

  W_ALWAYS_INLINE void SkipLine(WToken& ref_token, WUInt32& i, const WDeque<WToken>& tokens)
  {
    while (ref_token.m_iType != WTokenType::Newline && ref_token.m_iType != WTokenType::EndOfFile)
    {
      ref_token = tokens[++i];
    }
  }

  // Json parser for command_line.json files generated by cmake
  class CompileCommandsParser : public WJSONParser
  {
  public:
    struct CompileCommand
    {
      WString command;
      WString file;
    };

    void Initialize(WStreamReader& inout_stream)
    {
      SetInputStream(inout_stream);
    }

    WResult GetNextCommand(CompileCommand& out_command)
    {
      while (!m_bObjectOpen)
      {
        if (!ContinueParsing())
        {
          return W_FAILURE;
        }
      }

      while (m_bObjectOpen)
      {
        if (!ContinueParsing())
        {
          return W_FAILURE;
        }
      }

      out_command = m_Command;
      return W_SUCCESS;
    }

  private:
    // Inherited via WJSONParser
    virtual bool OnVariable(WStringView sVarName) override
    {
      bool needed = false;

      if (sVarName == "file")
      {
        needed = true;
        m_pNextVar = &m_Command.file;
      }
      else if (sVarName == "command")
      {
        needed = true;
        m_pNextVar = &m_Command.command;
      }

      if (!needed && sVarName != "directory" && sVarName != "output")
      {
        WStringBuilder fmt;
        fmt.SetFormat("Unknown variable '{0}'", sVarName);
        ParsingError(fmt.GetView(), false);
      }
      return needed;
    }

    virtual void OnReadValue(WStringView sValue) override
    {
      if (m_pNextVar == nullptr)
      {
        ParsingError("Unexpected value", true);
        return;
      }

      *m_pNextVar = sValue;
      m_pNextVar = nullptr;
    }

    virtual void OnReadValue(double fValue) override
    {
    }

    virtual void OnReadValue(bool bValue) override
    {
    }

    virtual void OnReadValueNULL() override
    {
    }

    virtual void OnBeginObject() override
    {
      if (!m_bOuterArrayOpen || m_bObjectOpen)
      {
        ParsingError("Unexpected object begin", true);
        return;
      }

      m_bObjectOpen = true;
      m_Command = {};
    }

    virtual void OnEndObject() override
    {
      if (!m_bObjectOpen)
      {
        ParsingError("Unexpected object end", true);
        return;
      }
      m_bObjectOpen = false;
    }

    virtual void OnBeginArray() override
    {
      if (!m_bOuterArrayOpen)
      {
        m_bOuterArrayOpen = true;
      }
      else
      {
        ParsingError("Unexpected array begin", true);
      }
    }

    virtual void OnEndArray() override
    {
      if (m_bOuterArrayOpen)
      {
        m_bOuterArrayOpen = false;
      }
      else
      {
        ParsingError("Unexpected array end", true);
      }
    }

    bool m_bOuterArrayOpen = false;
    bool m_bObjectOpen = false;
    WString* m_pNextVar = nullptr;
    CompileCommand m_Command;
  };

  // WOSFile::ExistsFile is quite slow, cache the results thread local to avoid lock contetion
  struct ExistsFileCache
  {
    static thread_local WHashTable<WString, bool> m_ExistsFileCache;

    static bool ExistsFile(WStringView sFile)
    {
      bool existedAlready = false;
      bool returnValue = false;
      {
        bool& result = m_ExistsFileCache.FindOrAdd(sFile, &existedAlready);
        if (!existedAlready)
        {
          result = WOSFile::ExistsFile(sFile);
        }
        returnValue = result;
      }
      return returnValue;
    }
  };

  thread_local WHashTable<WString, bool> ExistsFileCache::m_ExistsFileCache;

  // Task to parse a single header file
  // stores the results in the task, need to be extracted after finish using MoveOutDependencies
  class ParseHeaderFileTask : public WTask
  {
  public:
    ParseHeaderFileTask()
    {
      ConfigureTask("ParseHeaderFileTask", WTaskNesting::Maybe);
    }

    void Initialize(WStringView sPath)
    {
      m_sPath = sPath;
    }

    virtual void Execute() override;

    WStringView GetPath() const { return m_sPath; }
    WHashSet<WString>&& MoveOutDependencies() { return std::move(m_Dependencies); }

  private:
    WString m_sPath;
    WHashSet<WString> m_Dependencies;
    WTaskGroupID m_TaskGroup;
  };

  // Task to collect the dependencies of a single compilation unit
  // Might need to run multiple times (call HasWorkLeft to know if it needs to be executed again)
  // Needs to spawn other tasks when HasWorkLeft returns true: see ScheduleRemainingWork
  class CollectDependenciesTask : public WTask
  {
  public:
    CollectDependenciesTask()
    {
      ConfigureTask("CollectDependenciesTask", WTaskNesting::Maybe);
    }

    void Initialize(WStringView sPath, CompilationUnitContext& ref_context, WDependencyAnalysisApp& ref_app)
    {
      m_sPath = sPath;
      m_pContext = &ref_context;
      m_pApp = &ref_app;
    }

    void OnParsingFinished(WTaskGroupID taskGroupID);

    virtual void Execute() override;

    bool HasWorkLeft() const { return m_LeftoverFiles.GetCount() > 0; }

    void ScheduleRemainingWork();

  private:
    WStringView m_sPath;
    CompilationUnitContext* m_pContext = nullptr;
    WDependencyAnalysisApp* m_pApp = nullptr;
    WDynamicArray<WSharedPtr<ParseHeaderFileTask>> m_ParseTasks;
    WDynamicArray<WString> m_LeftoverFiles;
    WTaskGroupID m_ParseTaskGroup;
  };
} // namespace

/*
 * This application finds all dependencies of a given compile setup.
 *
 * Currently requires a compile_commands.json generated with cmake targeting the clang compiler
 *
 * Basic flow
 * - Parse the compile_command.json to find all .cpp files (compilation units)
 * - Parse each compilation unit, and find all headers it includes
 * - Parse all found headers and note their dependencies (storing only the unresolved paths)
 * - For each compilation unit resolve all dependencies by doing a breadth first search in parallel
 *   + Whenever we encounter a header file we have not seen yet, we need to parse it
 * - Write out the results into a json file. For each compilation units all header dependencies will be listed.
 */
class WDependencyAnalysisApp : public WApplication
{
private:
  friend CollectDependenciesTask;

  WString m_sCompileCommandsPath;
  bool m_bHadErrors;
  bool m_bHadSeriousWarnings;
  bool m_bHadWarnings;
  WDynamicArray<WString> m_IgnorePatterns;
  WString m_sOutputPath;

  CompilationUnitListType m_CompilationUnits;
  WMutex m_HeaderDependenciesMutex;
  WHashTable<WString, DependencyListType> m_HeaderDependencies;

  WMutex m_HeaderParsingScheduledMutex;
  WHashSet<WString> m_HeaderParsingScheduled;

public:
  using SUPER = WApplication;

  WDependencyAnalysisApp()
    : WApplication("DependencyAnalysis")
  {
    m_bHadErrors = false;
    m_bHadSeriousWarnings = false;
    m_bHadWarnings = false;
  }

  /// Makes sure the apps return value reflects whether there were any errors or warnings
  static void LogInspector(const WLoggingEventData& eventData)
  {
    WDependencyAnalysisApp* app = (WDependencyAnalysisApp*)WApplication::GetApplicationInstance();

    switch (eventData.m_EventType)
    {
      case WLogMsgType::ErrorMsg:
        app->m_bHadErrors = true;
        break;
      case WLogMsgType::SeriousWarningMsg:
        app->m_bHadSeriousWarnings = true;
        break;
      case WLogMsgType::WarningMsg:
        app->m_bHadWarnings = true;
        break;

      default:
        break;
    }
  }


  WResult ParseArray(const WVariant& value, WHashSet<WString>& ref_dst)
  {
    if (!value.CanConvertTo<WVariantArray>())
    {
      WLog::Error("Expected array");
      return W_FAILURE;
    }
    auto a = value.Get<WVariantArray>();
    const auto arraySize = a.GetCount();
    for (WUInt32 i = 0; i < arraySize; i++)
    {
      auto& el = a[i];
      if (!el.CanConvertTo<WString>())
      {
        WLog::Error("Value {0} at index {1} can not be converted to a string. Expected array of strings.", el, i);
        return W_FAILURE;
      }
      WStringBuilder file = el.Get<WString>();
      file.ToLower();
      ref_dst.Insert(file);
    }
    return W_SUCCESS;
  }

  virtual void AfterCoreSystemsStartup() override
  {
    WGlobalLog::AddLogWriter(WLogWriter::Console::LogMessageHandler);
    WGlobalLog::AddLogWriter(WLogWriter::VisualStudio::LogMessageHandler);
    WGlobalLog::AddLogWriter(LogInspector);


    WSystemInformation info = WSystemInformation::Get();
    const WInt32 iCpuCores = info.GetCPUCoreCount();
    WTaskSystem::SetWorkerThreadCount(iCpuCores);

    if (GetArgumentCount() < 2)
    {
      WLog::Info("DependencyAnalysis.exe [options] path/to/compile_commands.json");
      WLog::Info("");
      WLog::Info("-i [pattern] --ignorePattern [pattern]    ignore all cpp/h files containing this pattern");
      WLog::Info("-v           --verbose                    enable verbose logging");
      WLog::Info("-o [path]    --output [path]              path to the output json file");
      WLog::Info("");

      WLog::Error("No command line arguments given.");
      return;
    }

    // Add the empty data directory to access files via absolute paths
    WFileSystem::AddDataDirectory("", "App", ":", WDataDirUsage::AllowWrites).IgnoreResult();

    // pass the absolute path to the directory that should be scanned as the first parameter to this application
    WStringBuilder sCompileCommandsPath;

    auto numArgs = GetArgumentCount();
    auto shortIgnore = WStringView("-i");
    auto longIgnore = WStringView("--ignorePattern");
    auto shortVerbose = WStringView("-v");
    auto longVerbose = WStringView("--verbose");
    auto shortOutput = WStringView("-o");
    auto longOutput = WStringView("--output");
    for (WUInt32 argi = 1; argi < numArgs; argi++)
    {
      auto arg = WStringView(GetArgument(argi));
      if (arg == shortIgnore || arg == longIgnore)
      {
        if (numArgs <= argi + 1)
        {
          WLog::Error("Missing path for {0}", arg);
          return;
        }
        WStringBuilder ignorePattern = GetArgument(argi + 1);
        if (ignorePattern == shortIgnore || ignorePattern == longIgnore || ignorePattern == shortIgnore || ignorePattern == longIgnore || ignorePattern == shortOutput || ignorePattern == longOutput)
        {
          WLog::Error("Missing path for {0} found {1} instead", arg, ignorePattern.GetView());
          return;
        }
        argi++;
        ignorePattern.MakeCleanPath();
        m_IgnorePatterns.PushBack(ignorePattern);
      }
      else if (arg == shortVerbose || arg == longVerbose)
      {
        g_bVerbose = true;
      }
      else if (arg == shortOutput || arg == longOutput)
      {
        if (!m_sOutputPath.IsEmpty())
        {
          WLog::Error("Output path given multiple times");
          return;
        }
        if (numArgs <= argi + 1)
        {
          WLog::Error("Missing path for {0}", arg);
          return;
        }
        WStringBuilder outputPath = GetArgument(argi + 1);
        if (outputPath == shortIgnore || outputPath == longIgnore || outputPath == shortIgnore || outputPath == longIgnore || outputPath == shortOutput || outputPath == longOutput)
        {
          WLog::Error("Missing path for {0} found {1} instead", arg, outputPath.GetView());
          return;
        }
        if (!outputPath.IsAbsolutePath())
        {
          outputPath = WOSFile::GetCurrentWorkingDirectory();
          outputPath.AppendPath(GetArgument(argi + 1));
        }
        outputPath.MakeCleanPath();
        argi++;
        m_sOutputPath = outputPath;
      }
      else
      {
        if (sCompileCommandsPath.IsEmpty())
        {
          sCompileCommandsPath = arg;
          sCompileCommandsPath.MakeCleanPath();
        }
        else
        {
          WLog::Error("Currently only one directory is supported for searching. Did you forget -i|--includeDir? {0}", arg);
        }
      }
    }

    if (!WPathUtils::IsAbsolutePath(sCompileCommandsPath.GetData()))
      WLog::Error("The given path is not absolute: '{0}'", sCompileCommandsPath);

    m_sCompileCommandsPath = sCompileCommandsPath;

    if (m_sOutputPath.IsEmpty())
    {
      WLog::Error("No output path given. Use -o or --output");
    }
  }

  virtual void BeforeCoreSystemsShutdown() override
  {
    SetReturnCode(0);

    WGlobalLog::RemoveLogWriter(LogInspector);
    WGlobalLog::RemoveLogWriter(WLogWriter::Console::LogMessageHandler);
    WGlobalLog::RemoveLogWriter(WLogWriter::VisualStudio::LogMessageHandler);
  }

  static WResult ReadEntireFile(WStringView sFile, WStringBuilder& out_sContents)
  {
    out_sContents.Clear();

    WFileReader File;
    if (File.Open(sFile) == W_FAILURE)
    {
      WLog::Error("Could not open for reading: '{0}'", sFile);
      return W_FAILURE;
    }

    WDynamicArray<WUInt8> FileContent;

    WUInt8 Temp[4024];
    WUInt64 uiRead = File.ReadBytes(Temp, W_ARRAY_SIZE(Temp));

    while (uiRead > 0)
    {
      FileContent.PushBackRange(WArrayPtr<WUInt8>(Temp, (WUInt32)uiRead));

      uiRead = File.ReadBytes(Temp, W_ARRAY_SIZE(Temp));
    }

    FileContent.PushBack(0);

    if (!WUnicodeUtils::IsValidUtf8((const char*)&FileContent[0]))
    {
      WLog::Error("The file \"{0}\" contains characters that are not valid Utf8. This often happens when you type special characters in "
                   "an editor that does not save the file in Utf8 encoding.",
        sFile);
      return W_FAILURE;
    }

    out_sContents = (const char*)&FileContent[0];

    return W_SUCCESS;
  }

  static WResult FindIncludeFile(WStringView sPath, CompilationUnitContext& inout_context, WStringBuilder& out_sPath)
  {
    if (sPath.IsAbsolutePath())
    {
      out_sPath = sPath;
      out_sPath.MakeCleanPath();
      if (ExistsFileCache::ExistsFile(sPath))
      {
        return W_SUCCESS;
      }
      else
      {
        return W_FAILURE;
      }
    }

    for (auto& includeDir : inout_context.m_IncludeDirectories)
    {
      out_sPath = includeDir;
      out_sPath.AppendPath(sPath);
      out_sPath.MakeCleanPath();
      if (ExistsFileCache::ExistsFile(out_sPath))
      {
        return W_SUCCESS;
      }
    }

    return W_FAILURE;
  }

  bool IgnorePath(const WStringBuilder& sBuilder)
  {
    for (auto& ignore : m_IgnorePatterns)
    {
      if (sBuilder.FindSubString(ignore))
      {
        return true;
      }
    }
    return false;
  }

  void ParseCompileCommandsJson()
  {
    WFileReader reader;
    reader.Open(m_sCompileCommandsPath).AssertSuccess(); // TODO error handling

    CompileCommandsParser parser;
    parser.SetLogInterface(WLog::GetThreadLocalLogSystem());
    parser.Initialize(reader);

    WDynamicArray<WStringView> commandParts;

    WStringBuilder tmpPath;

    CompileCommandsParser::CompileCommand command;
    while (parser.GetNextCommand(command).Succeeded())
    {
      if (g_bVerbose)
      {
        WLog::Info("file: {0}", command.file);
      }
      tmpPath = command.file;
      tmpPath.MakeCleanPath();

      if (IgnorePath(tmpPath))
      {
        continue;
      }

      if (tmpPath.GetFileExtension().Compare_NoCase("cpp") != 0)
      {
        continue;
      }

      auto& context = m_CompilationUnits[tmpPath];

      WDynamicArray<WString> includeFiles;

      command.command.Split(false, commandParts, " ");
      const WUInt32 numParts = commandParts.GetCount();
      for (WUInt32 i = 0; i < numParts; i++)
      {
        auto part = commandParts[i];
        if (part.Compare_NoCase("-isystem") == 0)
        {
          i++;
          part = commandParts[i];
          tmpPath = part;
          tmpPath.MakeCleanPath();

          if (!IgnorePath(tmpPath)) // TODO make command line parameter
          {
            if (g_bVerbose)
            {
              WLog::Info(tmpPath);
            }
            context.m_IncludeDirectories.PushBack(tmpPath);
          }
        }
        else if (part.TrimWordStart("-include"))
        {
          tmpPath = part;
          tmpPath.MakeCleanPath();
          if (g_bVerbose)
          {
            WLog::Info(tmpPath);
          }
          includeFiles.PushBack(tmpPath);
        }
        else if (part.TrimWordStart("-I"))
        {
          tmpPath = part;
          tmpPath.MakeCleanPath();
          if (!IgnorePath(tmpPath))
          {
            if (g_bVerbose)
            {
              WLog::Info(tmpPath);
            }
            context.m_IncludeDirectories.PushBack(tmpPath);
          }
        }
      }

      for (auto& includeFile : includeFiles)
      {
        if (FindIncludeFile(includeFile.GetView(), context, tmpPath).Succeeded())
        {
          context.m_dependencies.Insert(tmpPath);
        }
        else
        {
          if (g_bVerbose)
          {
            WLog::Warning("Could not find include file '{0}' specified on the command line in any include path", includeFile);
          }
        }
      }
    }
  }

  void ParseCompilationUnits()
  {
    struct CompUnit
    {
      WStringView path;
      CompilationUnitContext* context;
    };
    WDynamicArray<CompUnit> compilationUnits;
    compilationUnits.Reserve(m_CompilationUnits.GetCount());

    for (auto& compilationUnit : m_CompilationUnits)
    {
      compilationUnits.PushBack({compilationUnit.Key().GetView(), &compilationUnit.Value()});
    }

    WTaskSystem::ParallelFor(
      compilationUnits.GetArrayPtr(), [this](WArrayPtr<CompUnit> compUnits)
      {
        WStringBuilder tmpPath;
        DependencyListType dependencies;
        for (auto& compUnit : compUnits)
        {
          WStringView currentFile = compUnit.path;

          W_LOG_BLOCK("CPP", currentFile);
          dependencies.Clear();
          FindDependencies(currentFile, dependencies);
          for (auto& dependency : dependencies)
          {
            if (!dependency.IsAbsolutePath())
            {
              if (FindIncludeFile(dependency.GetView(), *compUnit.context, tmpPath).Succeeded())
              {
                compUnit.context->m_dependencies.Insert(tmpPath);
              }
              else
              {
                if (g_bVerbose)
                {
                  WLog::Warning("Warning dependency '{0}' of '{1}' not found", dependency, currentFile);
                }
              }
            }
          }
        } },
      "ParseCompilationUnit");
  }

  void ParseHeaderFiles()
  {
    WStringBuilder tmpPath;
    WDynamicArray<WSharedPtr<ParseHeaderFileTask>> filesToCheckTasks;

    auto taskGroup = WTaskSystem::CreateTaskGroup(WTaskPriority::EarlyThisFrame);
    for (auto& compilationUnit : m_CompilationUnits)
    {
      for (auto& dependency : compilationUnit.Value().m_dependencies)
      {
        bool existed = false;
        if (auto& dependencies = m_HeaderDependencies.FindOrAdd(dependency.GetView(), &existed); !existed)
        {
          filesToCheckTasks.PushBack(W_DEFAULT_NEW(ParseHeaderFileTask));
          filesToCheckTasks.PeekBack()->Initialize(dependency.GetView());
          WTaskSystem::AddTaskToGroup(taskGroup, filesToCheckTasks.PeekBack());
        }
      }
    }

    WTaskSystem::StartTaskGroup(taskGroup);
    WTaskSystem::WaitForGroup(taskGroup);

    for (auto& task : filesToCheckTasks)
    {
      m_HeaderDependencies[task->GetPath()] = task->MoveOutDependencies();
    }
  }

  void CheckDependentFiles()
  {
    WDynamicArray<WSharedPtr<CollectDependenciesTask>> tasks;

    for (auto& compilationUnit : m_CompilationUnits)
    {
      tasks.PushBack(W_DEFAULT_NEW(CollectDependenciesTask));
      tasks.PeekBack()->Initialize(compilationUnit.Key(), compilationUnit.Value(), *this);
    }

    const WUInt32 totalNumTasks = tasks.GetCount();

    // First iteration
    {
      auto group = WTaskSystem::CreateTaskGroup(WTaskPriority::EarlyThisFrame);
      for (auto& task : tasks)
      {
        WTaskSystem::AddTaskToGroup(group, task);
      }
      WTaskSystem::StartTaskGroup(group);
      WTaskSystem::WaitForGroup(group);
    }

    while (true)
    {
      for (WUInt32 i = 0; i < tasks.GetCount();)
      {
        if (tasks[i]->HasWorkLeft())
        {
          tasks[i]->ScheduleRemainingWork();
          ++i;
        }
        else
        {
          tasks.RemoveAtAndSwap(i);
        }
      }

      if (tasks.GetCount() == 0) // If none of the tasks had work left, we are done
      {
        break;
      }

      WLog::Info("Collecting dependencies. Remaining {0} of {1} total", tasks.GetCount(), totalNumTasks);

      WTaskSystem::FinishFrameTasks(); // Wait for parsing tasks to finish before doing the next round of dependency collection

      auto group = WTaskSystem::CreateTaskGroup(WTaskPriority::EarlyThisFrame);
      for (auto& task : tasks)
      {
        WTaskSystem::AddTaskToGroup(group, task);
      }
      WTaskSystem::StartTaskGroup(group);
      WTaskSystem::WaitForGroup(group);
    }
  }

  void WriteOutResults()
  {
    WFileWriter FileOut;

    if (FileOut.Open(m_sOutputPath) == W_FAILURE)
    {
      WLog::Error("Could not open the file for writing: '{0}'", "results.json");
      return;
    }
    else
    {
      WStringBuilder json;
      json.Append("{\n");
      json.Append(" \"files\" : [\n");

      auto processFile = [this, &json](CompilationUnitListType::Iterator& file)
      {
        json.Append("    {\n");
        json.AppendFormat("      \"name\" : \"{0}\",\n", file.Key());
        json.Append("      \"dependencies\" :\n");
        json.Append("        [\n");

        auto count = (*file).Value().m_dependencies.GetCount();
        if (count > 0)
        {
          count--;
          auto depIt = (*file).Value().m_dependencies.GetIterator();

          for (WUInt32 i = 0; i < count; ++i, depIt.Next())
          {
            json.AppendFormat("       \"{0}\",\n", (*depIt).GetView());
          }
          json.AppendFormat("       \"{0}\"\n", (*depIt).GetView());
        }
        json.Append("        ]\n");
        json.Append("    }");
      };

      auto count = m_CompilationUnits.GetCount();
      if (count > 0)
      {
        count--;
        auto fileIt = m_CompilationUnits.GetIterator();
        for (WUInt32 i = 0; i < count; ++i, fileIt.Next())
        {
          processFile(fileIt);
          json.Append(",\n");
        }
        processFile(fileIt);
        json.Append("\n");
      }
      json.Append("  ]\n");
      json.Append("}\n");

      FileOut.WriteBytes(json.GetData(), json.GetElementCount()).AssertSuccess();
    }
  }

  static void FindDependencies(WStringView sCurrentFile, DependencyListType& inout_dependencies)
  {
    WStringBuilder fileContents;
    ReadEntireFile(sCurrentFile, fileContents).IgnoreResult();

    auto fileDir = sCurrentFile.GetFileDirectory();

    WTokenizer tokenizer;
    auto dataView = fileContents.GetView();
    auto start = dataView.GetStartPointer();
    auto elementCount = dataView.GetElementCount();
    if (elementCount >= 3 && WUnicodeUtils::SkipUtf8Bom(start))
    {
      elementCount -= 3;
    }
    tokenizer.Tokenize(WArrayPtr<const WUInt8>(reinterpret_cast<const WUInt8*>(start), elementCount), WLog::GetThreadLocalLogSystem());

    WStringView hash("#");
    WStringView include("include");
    WStringView openAngleBracket("<");
    WStringView closeAngleBracket(">");

    auto tokens = tokenizer.GetTokens();
    const auto numTokens = tokens.GetCount();
    for (WUInt32 i = 0; i < numTokens; i++)
    {
      auto curToken = tokens[i];
      while (curToken.m_iType == WTokenType::Whitespace)
      {
        curToken = tokens[++i];
      }
      if (curToken.m_iType == WTokenType::NonIdentifier && curToken.m_DataView == hash)
      {
        do
        {
          curToken = tokens[++i];
        } while (curToken.m_iType == WTokenType::Whitespace);

        if (curToken.m_iType == WTokenType::Identifier && curToken.m_DataView == include)
        {
          auto includeToken = curToken;
          do
          {
            curToken = tokens[++i];
          } while (curToken.m_iType == WTokenType::Whitespace);

          if (curToken.m_iType == WTokenType::String1)
          {
            // #include "bla"
            WStringBuilder absIncludePath;
            WStringBuilder relativePath;
            relativePath = curToken.m_DataView;
            relativePath.Trim("\"");
            relativePath.MakeCleanPath();
            absIncludePath = fileDir;
            absIncludePath.AppendPath(relativePath);

            if (!ExistsFileCache::ExistsFile(absIncludePath))
            {
              inout_dependencies.Insert(relativePath);
            }
            else
            {
              inout_dependencies.Insert(absIncludePath);
            }
          }
          else if (curToken.m_iType == WTokenType::NonIdentifier && curToken.m_DataView == openAngleBracket)
          {
            // #include <bla>
            bool error = false;
            auto startToken = curToken;
            do
            {
              curToken = tokens[++i];
              if (curToken.m_iType == WTokenType::Newline)
              {
                WLog::Error("Non-terminated '<' in #include {0} line {1}", sCurrentFile, includeToken.m_uiLine);
                error = true;
                break;
              }
            } while (curToken.m_iType != WTokenType::NonIdentifier || curToken.m_DataView != closeAngleBracket);

            if (error)
            {
              // in case of error skip the malformed line in hopes that we can recover from the error.
              do
              {
                curToken = tokens[++i];
              } while (curToken.m_iType != WTokenType::Newline);
            }
            else
            {
              WStringBuilder includePath;
              includePath = WStringView(startToken.m_DataView.GetEndPointer(), curToken.m_DataView.GetStartPointer());
              includePath.MakeCleanPath();
              inout_dependencies.Insert(includePath);
            }
          }
          else
          {
            // error
            WLog::Error("Can not parse #include statement in {0} line {1}", sCurrentFile, includeToken.m_uiLine);
          }
        }
        else
        {
          while (curToken.m_iType != WTokenType::Newline && curToken.m_iType != WTokenType::EndOfFile)
          {
            curToken = tokens[++i];
          }
        }
      }
      else
      {
        while (curToken.m_iType != WTokenType::Newline && curToken.m_iType != WTokenType::EndOfFile)
        {
          curToken = tokens[++i];
        }
      }
    }
  }

  virtual void Run() override
  {
    // something basic has gone wrong
    if (m_bHadSeriousWarnings || m_bHadErrors)
    {
      QuitApplication();
      return;
    }

    auto start = WTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      WLog::Info("Parse compile commands json");
    }
    ParseCompileCommandsJson();

    auto parseJsonEnd = WTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      WLog::Info("Parse compilation units");
    }
    ParseCompilationUnits();

    auto parseCompilationUnitsEnd = WTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      WLog::Info("Parse header files");
    }
    ParseHeaderFiles();

    auto parseHeaderFilesEnd = WTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      WLog::Info("Build dependencies");
    }
    CheckDependentFiles();

    auto checkDependendtFilesEnd = WTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      WLog::Info("Write out results");
    }
    WriteOutResults();

    auto writeOutResultsEnd = WTimestamp::CurrentTimestamp();

    WLog::Info("Time to parse compile commands json: {0}s", (parseJsonEnd - start).AsFloatInSeconds());
    WLog::Info("Time to parse compilation units: {0}s", (parseCompilationUnitsEnd - parseJsonEnd).AsFloatInSeconds());
    WLog::Info("Time to parse header files: {0}s", (parseHeaderFilesEnd - parseCompilationUnitsEnd).AsFloatInSeconds());
    WLog::Info("Time to build dependencies: {0}s", (checkDependendtFilesEnd - parseHeaderFilesEnd).AsFloatInSeconds());
    WLog::Info("Time to write out results: {0}s", (writeOutResultsEnd - checkDependendtFilesEnd).AsFloatInSeconds());
    WLog::Info("Total time taken: {0}s", (writeOutResultsEnd - start).AsFloatInSeconds());

    QuitApplication();
  }
};

void ParseHeaderFileTask::Execute()
{
  WDependencyAnalysisApp::FindDependencies(m_sPath, m_Dependencies);
}

void CollectDependenciesTask::Execute()
{
  W_ASSERT_DEBUG(m_pContext != nullptr && m_pApp != nullptr, "Task was not initialized properly");

  auto& compilationUnitDependencies = m_pContext->m_dependencies;

  WDynamicArray<WString> filesToCheck;
  if (m_LeftoverFiles.GetCount() > 0)
  {
    filesToCheck.Swap(m_LeftoverFiles);
    m_ParseTasks.Clear();
  }
  else
  {
    for (auto& include : compilationUnitDependencies)
    {
      filesToCheck.PushBack(include);
    }
  }

  WHashSet<WString> seenFiles;

  while (!filesToCheck.IsEmpty())
  {
    auto include = std::move(filesToCheck.PeekBack());
    filesToCheck.PopBack();

    if (seenFiles.Insert(include))
    {
      continue;
    }

    bool alreadyExisted = false;

    DependencyListType* headerDependencies = nullptr;
    if (!m_pApp->m_HeaderDependencies.TryGetValue(include.GetView(), headerDependencies))
    {
      {
        W_LOCK(m_pApp->m_HeaderParsingScheduledMutex);
        if (!m_pApp->m_HeaderParsingScheduled.Insert(include.GetView()))
        {
          if (m_ParseTasks.GetCount() == 0)
          {
            m_ParseTaskGroup = WTaskSystem::CreateTaskGroup(WTaskPriority::EarlyThisFrame, WMakeDelegate(&CollectDependenciesTask::OnParsingFinished, this));
          }
          WSharedPtr<ParseHeaderFileTask> task = W_DEFAULT_NEW(ParseHeaderFileTask);
          task->Initialize(include);
          WTaskSystem::AddTaskToGroup(m_ParseTaskGroup, task);
          m_ParseTasks.PushBack(std::move(task));
        }
      }
    }
    else
    {
      WStringBuilder tmpPath;
      for (auto& dependency : *headerDependencies)
      {
        if (m_pApp->FindIncludeFile(dependency.GetView(), *m_pContext, tmpPath).Succeeded())
        {
          if (!compilationUnitDependencies.Contains(tmpPath.GetView()))
          {
            compilationUnitDependencies.Insert(tmpPath);
            filesToCheck.PushBack(tmpPath);
          }
        }
        else
        {
          if (g_bVerbose)
          {
            WLog::Warning("Failed to find dependency '{0}' of compilation unit '{1}'", dependency, m_sPath);
          }
        }
      }
    }
  }
}

void CollectDependenciesTask::ScheduleRemainingWork()
{
  if (m_ParseTasks.GetCount() > 0)
  {
    WTaskSystem::StartTaskGroup(m_ParseTaskGroup);
  }
}

void CollectDependenciesTask::OnParsingFinished(WTaskGroupID taskGroupId)
{
  W_LOCK(m_pApp->m_HeaderDependenciesMutex);
  for (auto& task : m_ParseTasks)
  {
    bool alreadyExisted = false;
    auto& deps = m_pApp->m_HeaderDependencies.FindOrAdd(task->GetPath(), &alreadyExisted);
    if (!alreadyExisted)
    {
      deps = task->MoveOutDependencies();
    }
  }
}

W_APPLICATION_ENTRY_POINT(WDependencyAnalysisApp);
