#include <ProcGenPlugin/ProcGenPluginPCH.h>

W_STATICLINK_LIBRARY(ProcGenPlugin)
{
  if (bReturn)
    return;

  W_STATICLINK_REFERENCE(ProcGenPlugin_Components_Implementation_ProcPlacementComponent);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Components_Implementation_ProcVertexColorComponent);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Components_Implementation_ProcVolumeComponent);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Components_Implementation_ProcVolumeSplineComponent);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Components_Implementation_VolumeCollection);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Declarations);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Resources_Implementation_ProcGenGraphResource);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Startup);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Tasks_Implementation_FindPlacementTilesTask);
  W_STATICLINK_REFERENCE(ProcGenPlugin_Tasks_Implementation_PlacementTask);
}
