#pragma once

#include <EditorFramework/EditorFrameworkDLL.h>

#include <Foundation/Reflection/Implementation/StaticRTTI.h>
#include <Foundation/Strings/HashedString.h>
#include <Foundation/Strings/String.h>
#include <Foundation/Time/Timestamp.h>
#include <Foundation/Types/Bitflags.h>
#include <Foundation/Types/Uuid.h>

class WImage;
class WAssetFileHeader;
using WOsProcessID = WUInt32;

struct WAssetExistanceState
{
  using StorageType = WUInt8;

  enum Enum : WUInt8
  {
    FileAdded,
    FileRemoved,
    FileMoved,
    FileModified,
    FileUnchanged,
  };
};

struct WAssetDocumentFlags
{
  using StorageType = WUInt8;

  enum Enum
  {
    None = 0,
    AutoTransformOnSave = W_BIT(0),               ///< Every time the document is saved, TransformAsset is automatically executed
    DisableTransform = W_BIT(1),                  ///< If set, TransformAsset will not do anything
    OnlyTransformManually = W_BIT(2),             ///< The asset transformation is not done, unless explicitly requested for this asset
    SupportsThumbnail = W_BIT(3),                 ///< The asset supports thumbnail generation (InternalCreateThumbnail must be implemented).
    AutoThumbnailOnTransform = W_BIT(4),          ///< Thumbnail is automatically generated by the asset transform, and does not need to be explicitly created.
    SubAssetsSupportThumbnail = W_BIT(5),         ///< The sub-asset supports thumbnail generation (InternalCreateThumbnail must be implemented).
    SubAssetsAutoThumbnailOnTransform = W_BIT(6), ///< Thumbnails for sub-assets are automatically generated by the asset transform, and do not need to be explicitly created.
    Default = None
  };

  struct Bits
  {
    StorageType AutoTransformOnSave : 1;
    StorageType DisableTransform : 1;
    StorageType OnlyTransformManually : 1;
    StorageType SupportsThumbnail : 1;
    StorageType AutoThumbnailOnTransform : 1;
    StorageType SubAssetsSupportThumbnail : 1;
    StorageType SubAssetsAutoThumbnailOnTransform : 1;
  };
};

W_DECLARE_FLAGS_OPERATORS(WAssetDocumentFlags);

struct WTransformFlags
{
  using StorageType = WUInt8;

  enum Enum
  {
    None = 0,
    TriggeredManually = W_BIT(0),    ///< Transform triggered by user directly. Needs to be set to transform assets marked with
                                      ///< WAssetDocumentFlags::Enum::OnlyTransformManually.
    ForceTransform = W_BIT(1),       ///< Will transform the asset regardless of its current transform state.
    BackgroundProcessing = W_BIT(2), ///< If changes need to be made that requires re-saving the asset transform will be aborted and WTransformResult::NeedsImport is returned.
    Default = None
  };

  struct Bits
  {
    StorageType TriggeredManually : 1;
    StorageType ForceTransform : 1;
    StorageType BackgroundProcessing : 1;
  };
};
W_DECLARE_FLAGS_OPERATORS(WTransformFlags);

struct WSubAssetData
{
  WUuid m_Guid;
  WHashedString m_sSubAssetsDocumentTypeName;
  WString m_sName;
};

struct W_EDITORFRAMEWORK_DLL WAssetDocumentTypeDescriptor : public WDocumentTypeDescriptor
{
  WAssetDocumentTypeDescriptor() = default;
  ~WAssetDocumentTypeDescriptor() = default;

  WString m_sResourceFileExtension;
  WBitflags<WAssetDocumentFlags> m_AssetDocumentFlags;
};


struct WTransformResult
{
  using StorageType = WUInt8;

  enum Enum : WUInt8
  {
    Success = 0,
    Failure,
    NeedsImport,
    Default = Success,
  };
};
W_DECLARE_REFLECTABLE_TYPE(W_EDITORFRAMEWORK_DLL, WTransformResult);


struct W_EDITORFRAMEWORK_DLL WTransformStatus
{
  W_ALWAYS_INLINE explicit WTransformStatus()
    : m_Result(WTransformResult::Success)
  {
  }

  explicit WTransformStatus(const char* szError)
    : m_Result(WTransformResult::Failure)
    , m_sMessage(szError)
  {
  }

  explicit WTransformStatus(WTransformResult::Enum r, WStringView sError)
    : m_Result(r)
    , m_sMessage(sError)
  {
  }

  explicit WTransformStatus(WStringView sError)
    : m_Result(WTransformResult::Failure)
    , m_sMessage(sError)
  {
  }

  W_ALWAYS_INLINE WTransformStatus(WTransformResult::Enum r)
    : m_Result(r)
  {
  }

  W_ALWAYS_INLINE WTransformStatus(WStatus r)
    : m_Result(r.Succeeded() ? WTransformResult::Success : WTransformResult::Failure)
    , m_sMessage(r.GetMessageString())
  {
  }

  W_ALWAYS_INLINE WTransformStatus(WResult r)
    : m_Result(r.Succeeded() ? WTransformResult::Success : WTransformResult::Failure)
  {
  }

  W_ALWAYS_INLINE WTransformStatus(WResultEnum r)
    : m_Result(r == W_SUCCESS ? WTransformResult::Success : WTransformResult::Failure)
  {
  }

  explicit WTransformStatus(const WFormatString& fmt)
    : m_Result(WTransformResult::Failure)
  {
    WStringBuilder sMsg;
    m_sMessage = fmt.GetText(sMsg);
  }

  W_ALWAYS_INLINE bool Succeeded() const { return m_Result == WTransformResult::Success; }
  W_ALWAYS_INLINE bool Failed() const { return m_Result == WTransformResult::Failure; }

  WEnum<WTransformResult> m_Result;
  WString m_sMessage;
};
W_DECLARE_REFLECTABLE_TYPE(W_EDITORFRAMEWORK_DLL, WTransformStatus);

W_ALWAYS_INLINE WResult WToResult(const WTransformStatus& result)
{
  return result.m_Result == WTransformResult::Success ? W_SUCCESS : W_FAILURE;
}

/// Used by WEditorProcessorProcess to define the current state of one of the running WEditorProcessor processes managed by the WAssetProcessor.
/// \sa WAssetProcessor
struct WEditorProcessorState
{
  bool operator==(const WEditorProcessorState& rhs)
  {
    return m_uiProcessID == rhs.m_uiProcessID && m_bConnected == rhs.m_bConnected && m_bRunning == rhs.m_bRunning && m_bCrashed == rhs.m_bCrashed;
  }
  bool operator!=(const WEditorProcessorState& rhs)
  {
    return !(*this == rhs);
  }

  WOsProcessID m_uiProcessID = 0;
  bool m_bConnected = false; ///< The IPC pipe to the process is established.
  bool m_bRunning = false;   ///< The process is currently running working on an asset.
  bool m_bCrashed = false;   ///< The process has crashed.
};